version: '3'
services:
     mongodb:
         image: mongo
         ports: 
          - 27017:27017
         environment:
           - MONGO_INITDB_ROOT_USERNAME=mongo
           - MONGO_INITDB_ROOT_PASSWORD=mongo
     monigoexpress:
         image: mongo-express
         ports:
            - 8080:8081
         environment:
           - ME_CONFIG_MONGODB_SERVER=mongodb
           - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
           - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
